apiVersion: v1
kind: Service
metadata:
  name: balimidi-service
  labels:
    app: regapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
 
  selector:
    app: regapp    

  type: LoadBalancer
